<a href="https://colab.research.google.com/github/krakowiakpawel9/neural-network-course/blob/master/02_basics/02_activation_functions_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### Spis treści:
1. [Funkcje aktywacji](#a0)
    1. [Import bibliotek](#a1)
    2. [ReLU Function - Rectified Linear Unit](#a2)
    3. [Funkcja Sigmoid](#a3)
    4. [Tanh Function](#a4)
    5. [Funkcja Softmax](#a5)
  

### <a name='a0'></a> 1. Funkcje Aktywacji
#### <a name='a1'></a> 1.1 Import bibliotek

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

#### <a name='a2'></a> 1.2 ReLU Function - Rectified Linear Unit
####     $$f(x) = max(x, 0)$$


In [0]:
def max_relu(x):
    return max(x, 0.0)

In [3]:
for i in [-10., -5., 0., 5., 10.]:
    print(max_relu(i))

0.0
0.0
0.0
5.0
10.0


In [4]:
data = np.random.randn(50)
data = sorted(data)
data

[-2.8136157691200867,
 -1.9871476340765968,
 -1.9296150366473461,
 -1.5289184978788568,
 -1.416675215949612,
 -1.320969346576602,
 -1.313309085935145,
 -1.1649586404356194,
 -1.1453553921445523,
 -0.9715568980638966,
 -0.9568224030299164,
 -0.9318647928777192,
 -0.8223868093405523,
 -0.7582081301582552,
 -0.7545914677669675,
 -0.6957498586561501,
 -0.5919611586366341,
 -0.5430365994752512,
 -0.506000568919626,
 -0.4897616118345308,
 -0.4881302412258703,
 -0.4479356672328394,
 -0.4319422089841384,
 -0.38445282747822573,
 -0.2401007446570817,
 -0.13581305162684576,
 -0.1148358747252496,
 -0.054970910850089205,
 -0.002863522680085516,
 0.07245720632597333,
 0.10164441636229525,
 0.11509954764631321,
 0.15271197628204095,
 0.1538350579203188,
 0.24386783054154354,
 0.3032609250190681,
 0.4456564498556506,
 0.4770690075793256,
 0.6059852762880076,
 0.6081236800316271,
 0.6509479597385508,
 0.8004255432967158,
 0.9001860966637809,
 0.986241051141979,
 0.9981001092276282,
 1.0734041221418638,

In [5]:
# wygenerowanie danych do wykresu
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.072457,
       0.101644, 0.1151  , 0.152712, 0.153835, 0.243868, 0.303261,
       0.445656, 0.477069, 0.605985, 0.608124, 0.650948, 0.800426,
       0.900186, 0.986241, 0.9981  , 1.073404, 1.240055, 1.37827 ,
       1.604327, 2.264325])

In [6]:
df = pd.DataFrame({'data': data, 'max_relu_data': max_relu_data})
df.head()

data  max_relu_data
0 -2.813616            0.0
1 -1.987148            0.0
2 -1.929615            0.0
3 -1.528918            0.0
4 -1.416675            0.0

In [7]:
px.line(df, x='data', y='max_relu_data', width=700, height=400, title='ReLU Function')

#### <a name='a3'></a> 1.3 Funkcja Sigmoid
####    $$f(x) = \frac{1}{1 + e^{-x}}$$

In [0]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [9]:
for i in [-5., -3., -1., 0., 1., 3., 5.]:
    print(sigmoid(i))

0.0066928509242848554
0.04742587317756678
0.2689414213699951
0.5
0.7310585786300049
0.9525741268224334
0.9933071490757153


In [10]:
data = 3 * np.random.randn(50)
data = sorted(data)
data

[-6.638416010126644,
 -5.156208524906038,
 -4.727633509592917,
 -4.421910833619663,
 -4.144281255486029,
 -4.094375174952774,
 -3.965694669350836,
 -3.8508174462540685,
 -3.199156578167883,
 -2.9995053585772267,
 -2.8140354805929775,
 -2.7769774756451597,
 -2.749684038858634,
 -2.6868173437458585,
 -2.1329662330176444,
 -1.8063090687848598,
 -1.4444267535176047,
 -1.1948307733321144,
 -0.9841288154734427,
 -0.847258252877121,
 -0.7958699390084413,
 -0.5661565394685686,
 -0.3960805006808751,
 -0.28585305643734005,
 -0.24711323185745848,
 -0.16320432444256466,
 -0.012657872951239272,
 0.40239891093656466,
 0.4222917093973759,
 0.8030544033905254,
 1.2862707775810367,
 1.5166835636205274,
 1.6730705458530144,
 1.7832156290298928,
 1.891281686664269,
 1.9650974747214938,
 1.9721238720122258,
 2.0211511599348464,
 2.083745027284369,
 2.430870755510352,
 2.966329336974262,
 3.009121544373877,
 3.1148131174064257,
 3.1472588267518047,
 3.355100317478951,
 4.429615769581719,
 4.605774816099148

In [11]:
sigmoid_data = [sigmoid(x) for x in sorted(data)]
sigmoid_data

[0.001307387702104298,
 0.005730482820484129,
 0.008769793804321491,
 0.011868700788219395,
 0.015607375187099277,
 0.016392949009231852,
 0.018602261328236662,
 0.020819673354720892,
 0.03919747459161387,
 0.0474482244279501,
 0.05657042057014349,
 0.05858102337768751,
 0.06010449695319964,
 0.06375573051061591,
 0.10593372592781544,
 0.14108480010261587,
 0.1908607762917736,
 0.23239606934117377,
 0.272073305061217,
 0.3000083176430045,
 0.31090967142048925,
 0.3621241554590346,
 0.40225440490746334,
 0.42901940926178334,
 0.43853415820511393,
 0.4592892419305113,
 0.4968355740128992,
 0.5992638875489419,
 0.6040315055347079,
 0.6906274682208253,
 0.7835153107563826,
 0.820049599225106,
 0.8419847753813073,
 0.8560934769635025,
 0.8689015985969738,
 0.8770835581072219,
 0.8778390550507312,
 0.8829999890623238,
 0.8893132137087065,
 0.9191512641790782,
 0.9510296085566795,
 0.9529845107467709,
 0.9574996529738217,
 0.9588005759650821,
 0.9662714558113494,
 0.9882213224029293,
 0.99010

In [12]:
df = pd.DataFrame({'data': data, 'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -6.638416      0.001307
1 -5.156209      0.005730
2 -4.727634      0.008770
3 -4.421911      0.011869
4 -4.144281      0.015607

In [13]:
px.line(df, x='data', y='sigmoid_data', width=700, height=400, title='Sigmoid Function')

#### <a name='a4'></a> 1.4 Tanh Function

####   $$tanh (x) = \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [0]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [15]:
data = 2 * np.random.randn(100)
data = sorted(data)
data

[-5.652479757530161,
 -5.3004005700423935,
 -5.1338900527192255,
 -3.756998109339799,
 -3.0814360659911206,
 -3.009869521780436,
 -2.9530372741454425,
 -2.797133830482876,
 -2.625202429571104,
 -2.481713299309981,
 -2.4519048730839605,
 -2.2605982749469273,
 -2.2509976842499224,
 -2.239347816234081,
 -2.0967677509991933,
 -1.9893582764580804,
 -1.9730544262967458,
 -1.9536686029205925,
 -1.7130365331401434,
 -1.5900846688672978,
 -1.543497893657241,
 -1.534882365018966,
 -1.5252483787115811,
 -1.4559801242280426,
 -1.4365918126144461,
 -1.3185504231825382,
 -1.2736157998081419,
 -1.2505134740859163,
 -1.2326876358706709,
 -1.2295639378538687,
 -1.2164497442731772,
 -1.1622435025640396,
 -1.1491987665296757,
 -1.068362640922218,
 -1.0546833731424325,
 -1.034200851807751,
 -0.9800778147432223,
 -0.9301126299491559,
 -0.9204729725220782,
 -0.9111102314183231,
 -0.8943215474029181,
 -0.8648000477731925,
 -0.7717477920782988,
 -0.677276426956825,
 -0.6476805558148954,
 -0.5240681070834275,


In [16]:
tanh_data = [tanh(x) for x in sorted(data)]
tanh_data

[-0.9999753768782058,
 -0.9999502091265743,
 -0.9999305336196688,
 -0.9989098001889447,
 -0.9957964628594707,
 -0.9951511766819552,
 -0.9945690788679669,
 -0.9925893172400004,
 -0.9895639525373425,
 -0.9861191355710063,
 -0.985272716028306,
 -0.9784820251410912,
 -0.9780694367175313,
 -0.977558261987651,
 -0.9702631537489517,
 -0.9632679694227463,
 -0.9620735679998155,
 -0.9606037538405807,
 -0.9370190419384518,
 -0.9201623129546035,
 -0.9127062710681934,
 -0.9112563946814528,
 -0.9096079362155055,
 -0.8968690354171963,
 -0.8930095507364392,
 -0.8664229866790772,
 -0.8547746214967197,
 -0.848427563023144,
 -0.8433571382689385,
 -0.8424527949564451,
 -0.838603791379223,
 -0.8217696787505017,
 -0.8174884727631396,
 -0.7888435464432734,
 -0.7836204981660786,
 -0.7755876886230789,
 -0.7530995882554687,
 -0.7306464035244695,
 -0.72612108854165,
 -0.7216647034218919,
 -0.713521670794587,
 -0.698722521886935,
 -0.6479446117004994,
 -0.5897459347680298,
 -0.5701064611164438,
 -0.48083368113793

In [17]:
df = pd.DataFrame({'data': data, 'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -5.652480  -0.999975
1 -5.300401  -0.999950
2 -5.133890  -0.999931
3 -3.756998  -0.998910
4 -3.081436  -0.995796

In [18]:
px.line(df, x='data', y='tanh_data', width=700, height=400, title='Tanh Function')

#### <a name='a5'></a> 1.5 Softmax Function

####   $$S(x_i)=\frac{e^{x_{i}}}{\sum_{j=1}^{N}e^{x_j}},\ \ dla\ i = 1,...,N$$

####   $$S(x_1)=\frac{e^{x_{1}}}{\sum_{j=1}^{N}e^{x_j}}$$

In [0]:
def softmax(x):
    e_x = np.exp(x)
    denominator = np.sum(e_x, axis=1)
    denominator = denominator[:, np.newaxis]
    return e_x / denominator

In [20]:
data = np.random.randn(4, 5)
data

array([[-0.351259, -0.917952,  1.254228,  0.508378,  1.321029],
       [ 0.702423,  0.534806, -1.257751,  0.148698, -0.449673],
       [ 0.692516,  0.188151, -2.369486, -0.251164,  2.830567],
       [ 0.217531,  1.288792,  0.486272,  0.857413,  0.279405]])

In [21]:
result = softmax(data)
result

array([[0.070253, 0.039861, 0.349879, 0.165958, 0.374049],
       [0.347549, 0.293915, 0.048947, 0.199773, 0.109816],
       [0.095032, 0.057389, 0.004447, 0.036986, 0.806146],
       [0.122138, 0.356528, 0.159795, 0.231605, 0.129934]])

In [22]:
result.sum(axis=1)

array([1., 1., 1., 1.])

Krok po kroku

In [23]:
np.exp(data)

array([[ 0.703802,  0.399336,  3.50513 ,  1.662593,  3.747274],
       [ 2.018637,  1.707118,  0.284293,  1.160323,  0.637836],
       [ 1.998739,  1.207015,  0.093529,  0.777895, 16.955074],
       [ 1.243004,  3.628401,  1.626242,  2.357054,  1.322343]])

In [24]:
denominator = np.sum(np.exp(data), axis=1)
denominator

array([10.018134,  5.808207, 21.032252, 10.177044])

In [25]:
denominator = denominator[:, np.newaxis]
denominator

array([[10.018134],
       [ 5.808207],
       [21.032252],
       [10.177044]])

In [26]:
np.exp(data) / denominator

array([[0.070253, 0.039861, 0.349879, 0.165958, 0.374049],
       [0.347549, 0.293915, 0.048947, 0.199773, 0.109816],
       [0.095032, 0.057389, 0.004447, 0.036986, 0.806146],
       [0.122138, 0.356528, 0.159795, 0.231605, 0.129934]])